DROP TABLE OM_FILE_EXT
GO

CREATE TABLE OM_FILE_EXT
(
FILENO INT,
FILENAME VARCHAR(40)
)
GO

INSERT INTO OM_FILE_EXT VALUES (1, 'ROBER34.TXT')
INSERT INTO OM_FILE_EXT VALUES (2, 'employee.EXE')
INSERT INTO OM_FILE_EXT VALUES (3, 'TESTING.DOC')
INSERT INTO OM_FILE_EXT VALUES (4, 'book.XLS')
INSERT INTO OM_FILE_EXT VALUES (5, 'ROBIN.TXT')
INSERT INTO OM_FILE_EXT VALUES (6, 'CARLOS.CSV')
INSERT INTO OM_FILE_EXT VALUES (7, 'ROB.CSV')
INSERT INTO OM_FILE_EXT VALUES (8, 'CAT.XLS')
INSERT INTO OM_FILE_EXT VALUES (9, 'GINGER.JPG')
INSERT INTO OM_FILE_EXT VALUES (10, 'BOBBY.TXT')

SELECT * FROM OM_FILE_EXT

--EXAMPLE 1
BEGIN TRAN
DELETE FROM OM_FILE_EXT WHERE FILENO IN (1,2,3)
COMMIT TRAN

DELETE FROM OM_FILE_EXT WHERE FILENO IN (1,2,3)


BEGIN TRAN
DELETE FROM OM_FILE_EXT WHERE FILENO IN (1,2,3)
rollback TRAN


BEGIN TRAN
DECLARE @v_Count INT
DELETE FROM OM_FILE_EXT WHERE FILENO IN (1,2,3)
SET @v_Count = @@ROWCOUNT
IF @v_Count > 3  -- 3 > 3 --> TRUE OR FALSE
COMMIT TRAN
ELSE
ROLLBACK TRAN
end







SELECT * FROM OM_FILE_EXT

--EXAMPLE 2
BEGIN TRAN
DELETE FROM OM_FILE_EXT WHERE FILENO IN (4, 5)
ROLLBACK TRAN

--RUN IN NEXT WINDOW
SELECT * FROM OM_FILE_EXT WITH (NOLOCK)

SELECT * FROM OM_FILE_EXT






--EXAMPLE 3

DROP TABLE OM_FILE_EXT_RAW

CREATE TABLE OM_FILE_EXT_RAW
(
FILENO INT,
FILENAME VARCHAR(40),
FILE_NAME_ID INT

)

INSERT INTO OM_FILE_EXT_RAW VALUES (1, 'ROBER34.TXT',1)
INSERT INTO OM_FILE_EXT_RAW VALUES (2, 'employee.EXE',1)
INSERT INTO OM_FILE_EXT_RAW VALUES (3, 'TESTING.DOC',1)
INSERT INTO OM_FILE_EXT_RAW VALUES (4, 'book.XLS',2)
INSERT INTO OM_FILE_EXT_RAW VALUES (5, 'ROBIN.TXT',2)
INSERT INTO OM_FILE_EXT_RAW VALUES (6, 'CARLOS.CSV',2)
INSERT INTO OM_FILE_EXT_RAW VALUES (7, 'ROB.CSV',2)
INSERT INTO OM_FILE_EXT_RAW VALUES (8, 'CAT.XLS',2)
INSERT INTO OM_FILE_EXT_RAW VALUES (9, 'GINGER.JPG',2)
INSERT INTO OM_FILE_EXT_RAW VALUES (10, 'BOBBY.TXT',2)

SELECT * FROM OM_FILE_EXT_RAW





--STAGE TABLE
DROP TABLE OM_FILE_EXT_STAGE

CREATE TABLE OM_FILE_EXT_STAGE
(
FILENO INT,
FILENAME VARCHAR(40),
FILE_NAME_ID INT
)



INSERT INTO OM_FILE_EXT_STAGE
SELECT * FROM OM_FILE_EXT_RAW


TRUNCATE TABLE OM_FILE_EXT_STAGE
SELECT * FROM OM_FILE_EXT_STAGE
SELECT * FROM OM_FILE_EXT_RAW

---------------------
drop proc OM_LOAD_FILE

ALTER PROC OM_LOAD_FILE
AS
BEGIN

BEGIN TRAN A
DECLARE @RAW_COUNT INT, @v_Count INT
SELECT @RAW_COUNT = COUNT(*) FROM OM_FILE_EXT_RAW WHERE FILE_NAME_ID IN (SELECT MAX(FILE_NAME_ID) FROM OM_FILE_EXT_RAW )
--SELECT  COUNT(*) FROM OM_FILE_EXT_RAW WHERE FILE_NAME_ID IN (SELECT MAX(FILE_NAME_ID) FROM OM_FILE_EXT_RAW )

INSERT INTO OM_FILE_EXT_STAGE
SELECT * FROM OM_FILE_EXT_RAW
WHERE FILE_NAME_ID IN (SELECT Max(FILE_NAME_ID) FROM OM_FILE_EXT_RAW )

SET @v_Count = @@ROWCOUNT

--SELECT   @RAW_COUNT, @v_count


   IF @v_count <> @RAW_COUNT
BEGIN
ROLLBACK TRAN A
PRINT 'DATA GET ROLLBACK'
END

  IF @@TRANCOUNT > 0
 BEGIN
 COMMIT TRAN A
 PRINT FORMATMESSAGE('Committing Tran with ROWCOUNT = %i.',  @v_Count);
 END

END --END OF SP


EXEC OM_LOAD_FILE

SELECT * FROM OM_FILE_EXT_STAGE









--EXAMPLE 3
--SAVE POINT

BEGIN TRANSACTION
--SAVE TRANSACTION S1
DELETE FROM OM_FILE_EXT_RAW where FILE_NAME_ID = 1

SAVE TRANSACTION S2
DELETE FROM OM_FILE_EXT_RAW where FILE_NAME_ID = 2

INSERT INTO OM_FILE_EXT_RAW VALUES (19, 'GINGER.JPG',2)
INSERT INTO OM_FILE_EXT_RAW VALUES (110, 'BOBBY.TXT',2)

ROLLBACK TRANSACTION S2 -- ROLLBACK ON UNDO FROM "SAVE TRANSACTION S2"
commit tran


--ROLLBACK TRANSACTION S1

--RUN FOLLOWING IN NEXT INSTANCE, YOU CAN NOT SEE DATA JUST RUNNING SELECT * FROM OM_FILE_EXT_RAW
SELECT * FROM OM_FILE_EXT_RAW WITH (NOLOCK)


